services:
  curtain-gateway:
    build: .
    container_name: curtain-gateway
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env

  mqtt-broker:
    image: eclipse-mosquitto:latest
    container_name: mqtt-broker
    restart: unless-stopped
    ports:
      - "1883:1883"
    env_file:
      - .env
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log
    entrypoint:
      - sh
      - -c
      - |
        if [ ! -f /mosquitto/config/passwd ]; then
          echo 'Генерация файла паролей MQTT...'
          mosquitto_passwd -b -c /mosquitto/config/passwd "$$MQTT_USER" "$$MQTT_PASS"
          chown 1883:1883 /mosquitto/config/passwd
        fi
        exec /docker-entrypoint.sh mosquitto -c /mosquitto/config/mosquitto.conf

volumes:
  mosquitto-data:
  mosquitto-log:
