
esphome:
  name: shpora-mqtt

esp32:
  board: esp32dev
  framework:
    type: arduino

wifi:
  ssid: "GoshaHome"
  password: "1122334455"

mqtt:
  broker: 192.168.88.252  # IP-адрес вашего мини-ПК
  username: "jezv"
  password: "1122334455"
  topic_prefix: shpora_curtain

logger:

stepper:
  - platform: uln2003
    id: my_stepper
    pin_a: GPIO19
    pin_b: GPIO18
    pin_c: GPIO5
    pin_d: GPIO17
    max_speed: 250 steps/s
    sleep_when_done: true

# ИСПРАВЛЕНО: Используем template вместо feedback
cover:
  - platform: template
    name: "Штора"
    id: curtain
    device_class: curtain
    
    # Оптимизируем под бинарное управление (Алиса присылает только Открыть/Закрыть)
    open_action:
      - stepper.set_target:
          id: my_stepper
          target: 4000
    close_action:
      - stepper.set_target:
          id: my_stepper
          target: 0
    stop_action:
      - stepper.set_target:
          id: my_stepper
          target: !lambda "return id(my_stepper).current_position;"
          
    # Обязательная строка для template cover, чтобы ESPHome понимал статус шторы
    optimistic: true
